// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

package rpcx

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PullEnableUsersRequest struct {
	NodeId               int64    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UpdateTime           int64    `protobuf:"varint,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullEnableUsersRequest) Reset()         { *m = PullEnableUsersRequest{} }
func (m *PullEnableUsersRequest) String() string { return proto.CompactTextString(m) }
func (*PullEnableUsersRequest) ProtoMessage()    {}
func (*PullEnableUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{0}
}

func (m *PullEnableUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullEnableUsersRequest.Unmarshal(m, b)
}
func (m *PullEnableUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullEnableUsersRequest.Marshal(b, m, deterministic)
}
func (m *PullEnableUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullEnableUsersRequest.Merge(m, src)
}
func (m *PullEnableUsersRequest) XXX_Size() int {
	return xxx_messageInfo_PullEnableUsersRequest.Size(m)
}
func (m *PullEnableUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullEnableUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullEnableUsersRequest proto.InternalMessageInfo

func (m *PullEnableUsersRequest) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *PullEnableUsersRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PullEnableUsersRequest) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type PullEnableUsersResponse struct {
	EnableUsers          []*EnableUser `protobuf:"bytes,1,rep,name=enable_users,json=enableUsers,proto3" json:"enable_users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PullEnableUsersResponse) Reset()         { *m = PullEnableUsersResponse{} }
func (m *PullEnableUsersResponse) String() string { return proto.CompactTextString(m) }
func (*PullEnableUsersResponse) ProtoMessage()    {}
func (*PullEnableUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{1}
}

func (m *PullEnableUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullEnableUsersResponse.Unmarshal(m, b)
}
func (m *PullEnableUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullEnableUsersResponse.Marshal(b, m, deterministic)
}
func (m *PullEnableUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullEnableUsersResponse.Merge(m, src)
}
func (m *PullEnableUsersResponse) XXX_Size() int {
	return xxx_messageInfo_PullEnableUsersResponse.Size(m)
}
func (m *PullEnableUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullEnableUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullEnableUsersResponse proto.InternalMessageInfo

func (m *PullEnableUsersResponse) GetEnableUsers() []*EnableUser {
	if m != nil {
		return m.EnableUsers
	}
	return nil
}

type EnableUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Limit                uint64   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableUser) Reset()         { *m = EnableUser{} }
func (m *EnableUser) String() string { return proto.CompactTextString(m) }
func (*EnableUser) ProtoMessage()    {}
func (*EnableUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{2}
}

func (m *EnableUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableUser.Unmarshal(m, b)
}
func (m *EnableUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableUser.Marshal(b, m, deterministic)
}
func (m *EnableUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableUser.Merge(m, src)
}
func (m *EnableUser) XXX_Size() int {
	return xxx_messageInfo_EnableUser.Size(m)
}
func (m *EnableUser) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableUser.DiscardUnknown(m)
}

var xxx_messageInfo_EnableUser proto.InternalMessageInfo

func (m *EnableUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EnableUser) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *EnableUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EnableUser) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PushUserTrafficRequest struct {
	TrafficInfo          []*TrafficInfo `protobuf:"bytes,1,rep,name=traffic_info,json=trafficInfo,proto3" json:"traffic_info,omitempty"`
	NodeId               int64          `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token                string         `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PushUserTrafficRequest) Reset()         { *m = PushUserTrafficRequest{} }
func (m *PushUserTrafficRequest) String() string { return proto.CompactTextString(m) }
func (*PushUserTrafficRequest) ProtoMessage()    {}
func (*PushUserTrafficRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{3}
}

func (m *PushUserTrafficRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushUserTrafficRequest.Unmarshal(m, b)
}
func (m *PushUserTrafficRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushUserTrafficRequest.Marshal(b, m, deterministic)
}
func (m *PushUserTrafficRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushUserTrafficRequest.Merge(m, src)
}
func (m *PushUserTrafficRequest) XXX_Size() int {
	return xxx_messageInfo_PushUserTrafficRequest.Size(m)
}
func (m *PushUserTrafficRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushUserTrafficRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushUserTrafficRequest proto.InternalMessageInfo

func (m *PushUserTrafficRequest) GetTrafficInfo() []*TrafficInfo {
	if m != nil {
		return m.TrafficInfo
	}
	return nil
}

func (m *PushUserTrafficRequest) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *PushUserTrafficRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TrafficInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Upload               uint64   `protobuf:"varint,3,opt,name=upload,proto3" json:"upload,omitempty"`
	Download             uint64   `protobuf:"varint,4,opt,name=download,proto3" json:"download,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficInfo) Reset()         { *m = TrafficInfo{} }
func (m *TrafficInfo) String() string { return proto.CompactTextString(m) }
func (*TrafficInfo) ProtoMessage()    {}
func (*TrafficInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{4}
}

func (m *TrafficInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficInfo.Unmarshal(m, b)
}
func (m *TrafficInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficInfo.Marshal(b, m, deterministic)
}
func (m *TrafficInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficInfo.Merge(m, src)
}
func (m *TrafficInfo) XXX_Size() int {
	return xxx_messageInfo_TrafficInfo.Size(m)
}
func (m *TrafficInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficInfo proto.InternalMessageInfo

func (m *TrafficInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *TrafficInfo) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *TrafficInfo) GetUpload() uint64 {
	if m != nil {
		return m.Upload
	}
	return 0
}

func (m *TrafficInfo) GetDownload() uint64 {
	if m != nil {
		return m.Download
	}
	return 0
}

type PushUserTrafficResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushUserTrafficResponse) Reset()         { *m = PushUserTrafficResponse{} }
func (m *PushUserTrafficResponse) String() string { return proto.CompactTextString(m) }
func (*PushUserTrafficResponse) ProtoMessage()    {}
func (*PushUserTrafficResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{5}
}

func (m *PushUserTrafficResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushUserTrafficResponse.Unmarshal(m, b)
}
func (m *PushUserTrafficResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushUserTrafficResponse.Marshal(b, m, deterministic)
}
func (m *PushUserTrafficResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushUserTrafficResponse.Merge(m, src)
}
func (m *PushUserTrafficResponse) XXX_Size() int {
	return xxx_messageInfo_PushUserTrafficResponse.Size(m)
}
func (m *PushUserTrafficResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushUserTrafficResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushUserTrafficResponse proto.InternalMessageInfo

type SsNodeReuqest struct {
	NodeId               int64    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SsNodeReuqest) Reset()         { *m = SsNodeReuqest{} }
func (m *SsNodeReuqest) String() string { return proto.CompactTextString(m) }
func (*SsNodeReuqest) ProtoMessage()    {}
func (*SsNodeReuqest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{6}
}

func (m *SsNodeReuqest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SsNodeReuqest.Unmarshal(m, b)
}
func (m *SsNodeReuqest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SsNodeReuqest.Marshal(b, m, deterministic)
}
func (m *SsNodeReuqest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SsNodeReuqest.Merge(m, src)
}
func (m *SsNodeReuqest) XXX_Size() int {
	return xxx_messageInfo_SsNodeReuqest.Size(m)
}
func (m *SsNodeReuqest) XXX_DiscardUnknown() {
	xxx_messageInfo_SsNodeReuqest.DiscardUnknown(m)
}

var xxx_messageInfo_SsNodeReuqest proto.InternalMessageInfo

func (m *SsNodeReuqest) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *SsNodeReuqest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SsNodeResponse struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SsNodeResponse) Reset()         { *m = SsNodeResponse{} }
func (m *SsNodeResponse) String() string { return proto.CompactTextString(m) }
func (*SsNodeResponse) ProtoMessage()    {}
func (*SsNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{7}
}

func (m *SsNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SsNodeResponse.Unmarshal(m, b)
}
func (m *SsNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SsNodeResponse.Marshal(b, m, deterministic)
}
func (m *SsNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SsNodeResponse.Merge(m, src)
}
func (m *SsNodeResponse) XXX_Size() int {
	return xxx_messageInfo_SsNodeResponse.Size(m)
}
func (m *SsNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SsNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SsNodeResponse proto.InternalMessageInfo

func (m *SsNodeResponse) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func init() {
	proto.RegisterType((*PullEnableUsersRequest)(nil), "club.vnet.rpcx.PullEnableUsersRequest")
	proto.RegisterType((*PullEnableUsersResponse)(nil), "club.vnet.rpcx.PullEnableUsersResponse")
	proto.RegisterType((*EnableUser)(nil), "club.vnet.rpcx.EnableUser")
	proto.RegisterType((*PushUserTrafficRequest)(nil), "club.vnet.rpcx.PushUserTrafficRequest")
	proto.RegisterType((*TrafficInfo)(nil), "club.vnet.rpcx.TrafficInfo")
	proto.RegisterType((*PushUserTrafficResponse)(nil), "club.vnet.rpcx.PushUserTrafficResponse")
	proto.RegisterType((*SsNodeReuqest)(nil), "club.vnet.rpcx.SsNodeReuqest")
	proto.RegisterType((*SsNodeResponse)(nil), "club.vnet.rpcx.SsNodeResponse")
}

func init() { proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90) }

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x55, 0x3e, 0x58, 0xd8, 0x49, 0xbb, 0x54, 0x16, 0xda, 0x86, 0x45, 0x54, 0xab, 0x1c, 0x20,
	0x5c, 0x72, 0x28, 0x67, 0x7a, 0x00, 0x71, 0xe8, 0x05, 0x15, 0xb7, 0x48, 0x88, 0xcb, 0x2a, 0xd9,
	0x4c, 0xb6, 0x16, 0x59, 0x3b, 0x8d, 0xed, 0x96, 0x7f, 0xc0, 0x5f, 0x41, 0xfc, 0x4a, 0x64, 0x3b,
	0xdd, 0x8f, 0x10, 0x84, 0x7a, 0x8a, 0x9f, 0x27, 0xe3, 0x79, 0xef, 0xf9, 0x25, 0x40, 0xb4, 0xc4,
	0x76, 0x21, 0xb1, 0xbd, 0x65, 0x4b, 0xcc, 0x9a, 0x56, 0x28, 0x41, 0x26, 0xcb, 0x5a, 0x17, 0xd9,
	0x2d, 0x47, 0x95, 0xb5, 0xcd, 0xf2, 0x47, 0xb2, 0x82, 0xe9, 0x85, 0xae, 0xeb, 0x8f, 0x3c, 0x2f,
	0x6a, 0xfc, 0x22, 0xb1, 0x95, 0x14, 0x6f, 0x34, 0x4a, 0x45, 0x8e, 0xe1, 0x31, 0x17, 0x25, 0x2e,
	0x58, 0x19, 0x7b, 0x73, 0x2f, 0x0d, 0xe8, 0xc8, 0xc0, 0xf3, 0x92, 0x3c, 0x83, 0x47, 0x4a, 0x7c,
	0x47, 0x1e, 0xfb, 0x73, 0x2f, 0x1d, 0x53, 0x07, 0xc8, 0x09, 0x80, 0x6e, 0xca, 0x5c, 0xe1, 0x15,
	0x5b, 0x63, 0x1c, 0xd8, 0x8e, 0x9d, 0x9d, 0xe4, 0x2b, 0x1c, 0xff, 0x35, 0x48, 0x36, 0x82, 0x4b,
	0x24, 0xef, 0xe0, 0x00, 0xed, 0xf6, 0xc2, 0x10, 0x96, 0xb1, 0x37, 0x0f, 0xd2, 0xe8, 0x74, 0x96,
	0xed, 0x53, 0xcd, 0xb6, 0xad, 0x34, 0xc2, 0xed, 0x31, 0x49, 0x01, 0xb0, 0x2d, 0x91, 0x09, 0xf8,
	0x1b, 0xc6, 0x3e, 0x2b, 0x09, 0x81, 0xb0, 0x11, 0xad, 0xb2, 0x64, 0x0f, 0xa9, 0x5d, 0x93, 0x19,
	0x3c, 0x69, 0x72, 0x29, 0xef, 0x44, 0x5b, 0x5a, 0xa6, 0x63, 0xba, 0xc1, 0x46, 0x5d, 0xcd, 0xd6,
	0x4c, 0xc5, 0xe1, 0xdc, 0x4b, 0x43, 0xea, 0x40, 0xf2, 0xd3, 0x33, 0x3e, 0xc9, 0x6b, 0x33, 0xe2,
	0xaa, 0xcd, 0xab, 0x8a, 0x2d, 0xef, 0x7d, 0x3a, 0x83, 0x03, 0xe5, 0x76, 0x16, 0x8c, 0x57, 0xa2,
	0x63, 0xff, 0xa2, 0xcf, 0xbe, 0xeb, 0x3a, 0xe7, 0x95, 0xa0, 0x91, 0xda, 0x82, 0x5d, 0x9f, 0xfd,
	0x61, 0x9f, 0x83, 0x1d, 0x9f, 0x93, 0x15, 0x44, 0x3b, 0x47, 0x91, 0x23, 0x08, 0xf4, 0x46, 0xaf,
	0x59, 0xee, 0x09, 0x0e, 0x3a, 0xc1, 0x53, 0x18, 0xe9, 0xa6, 0x16, 0xb9, 0x93, 0x1b, 0xd2, 0x0e,
	0x19, 0x23, 0x4a, 0x71, 0xc7, 0x6d, 0xc5, 0xe9, 0xdd, 0xe0, 0xe4, 0xb9, 0xb9, 0xb0, 0x9e, 0x62,
	0x77, 0x61, 0xc9, 0x19, 0x1c, 0x5e, 0xca, 0x4f, 0xa2, 0x44, 0x8a, 0xfa, 0xe6, 0xe1, 0x59, 0x49,
	0x52, 0x98, 0xdc, 0xf7, 0x77, 0x11, 0x98, 0xc2, 0x68, 0x8d, 0xea, 0x5a, 0xb8, 0xfe, 0x31, 0xed,
	0xd0, 0xe9, 0x2f, 0x1f, 0x22, 0xc3, 0xe0, 0xd2, 0x85, 0x98, 0x14, 0xf0, 0xb4, 0x97, 0x22, 0xf2,
	0xaa, 0xef, 0xf4, 0x70, 0x9e, 0x67, 0xaf, 0xff, 0xfb, 0x5e, 0xc7, 0xc5, 0xce, 0xd8, 0x13, 0x3e,
	0x34, 0x63, 0x28, 0x0b, 0x43, 0x33, 0x06, 0x1d, 0x24, 0x9f, 0xe1, 0xc8, 0x8c, 0x77, 0x2e, 0x7c,
	0x10, 0xbc, 0x62, 0x2b, 0xf2, 0xb2, 0xdf, 0xbc, 0xe7, 0xf1, 0xec, 0xe4, 0x5f, 0x65, 0x77, 0xe4,
	0xfb, 0x37, 0xd0, 0xfb, 0xb6, 0x2f, 0xbc, 0x6f, 0xa1, 0x79, 0xfe, 0xf6, 0x7b, 0x85, 0x62, 0x64,
	0xff, 0x05, 0x6f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x39, 0x13, 0xb5, 0x21, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	PullEnableUsers(ctx context.Context, in *PullEnableUsersRequest, opts ...grpc.CallOption) (*PullEnableUsersResponse, error)
	PushUserTraffic(ctx context.Context, in *PushUserTrafficRequest, opts ...grpc.CallOption) (*PushUserTrafficResponse, error)
	PullSsNodeConfig(ctx context.Context, in *SsNodeReuqest, opts ...grpc.CallOption) (*SsNodeResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) PullEnableUsers(ctx context.Context, in *PullEnableUsersRequest, opts ...grpc.CallOption) (*PullEnableUsersResponse, error) {
	out := new(PullEnableUsersResponse)
	err := c.cc.Invoke(ctx, "/club.vnet.rpcx.UserService/PullEnableUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PushUserTraffic(ctx context.Context, in *PushUserTrafficRequest, opts ...grpc.CallOption) (*PushUserTrafficResponse, error) {
	out := new(PushUserTrafficResponse)
	err := c.cc.Invoke(ctx, "/club.vnet.rpcx.UserService/PushUserTraffic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PullSsNodeConfig(ctx context.Context, in *SsNodeReuqest, opts ...grpc.CallOption) (*SsNodeResponse, error) {
	out := new(SsNodeResponse)
	err := c.cc.Invoke(ctx, "/club.vnet.rpcx.UserService/PullSsNodeConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	PullEnableUsers(context.Context, *PullEnableUsersRequest) (*PullEnableUsersResponse, error)
	PushUserTraffic(context.Context, *PushUserTrafficRequest) (*PushUserTrafficResponse, error)
	PullSsNodeConfig(context.Context, *SsNodeReuqest) (*SsNodeResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_PullEnableUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullEnableUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PullEnableUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.vnet.rpcx.UserService/PullEnableUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PullEnableUsers(ctx, req.(*PullEnableUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PushUserTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushUserTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PushUserTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.vnet.rpcx.UserService/PushUserTraffic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PushUserTraffic(ctx, req.(*PushUserTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PullSsNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SsNodeReuqest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PullSsNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/club.vnet.rpcx.UserService/PullSsNodeConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PullSsNodeConfig(ctx, req.(*SsNodeReuqest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "club.vnet.rpcx.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullEnableUsers",
			Handler:    _UserService_PullEnableUsers_Handler,
		},
		{
			MethodName: "PushUserTraffic",
			Handler:    _UserService_PushUserTraffic_Handler,
		},
		{
			MethodName: "PullSsNodeConfig",
			Handler:    _UserService_PullSsNodeConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service.proto",
}
