POST http://localhost:8080/shadowsocks/add HTTP/1.1
Content-Type: application/json

{
    "host":"0.0.0.0",
    "method":"aes-128-gcm",
    "password":"killer",
    "port":1091
}

###

POST http://localhost:8080/shadowsocks/start/1091

###
POST http://localhost:8080/shadowsocks/stop/1091

###
GET http://localhost:8080/shadowsocks

###
DELETE http://localhost:8080/shadowsocks/del/1091